In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import time

mushroom = pd.read_csv('mushrooms.csv')
mushroom.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

Attribute Information: (classes: edible=e, poisonous=p)

  *  cap-shape: bell=b,conical=c,convex=x,flat=f, knobbed=k,sunken=s

  *  cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s

  *  cap-color: brown=n,buff=b,cinnamon=c,gray=g,green=r,pink=p,purple=u,red=e,white=w,yellow=y

  *  bruises: bruises=t,no=f

  *  odor: almond=a,anise=l,creosote=c,fishy=y,foul=f,musty=m,none=n,pungent=p,spicy=s

  *  gill-attachment: attached=a,descending=d,free=f,notched=n

  * gill-spacing: close=c,crowded=w,distant=d

  *  gill-size: broad=b,narrow=n

  *  gill-color: black=k,brown=n,buff=b,chocolate=h,gray=g, green=r,orange=o,pink=p,purple=u,red=e,white=w,yellow=y

  *  stalk-shape: enlarging=e,tapering=t

  *  stalk-root: bulbous=b,club=c,cup=u,equal=e,rhizomorphs=z,rooted=r,missing=?

  *  stalk-surface-above-ring: fibrous=f,scaly=y,silky=k,smooth=s

  *  stalk-surface-below-ring: fibrous=f,scaly=y,silky=k,smooth=s

  *  stalk-color-above-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o,pink=p,red=e,white=w,yellow=y

  *  stalk-color-below-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o,pink=p,red=e,white=w,yellow=y

  *  veil-type: partial=p,universal=u

  *  veil-color: brown=n,orange=o,white=w,yellow=y

  *  ring-number: none=n,one=o,two=t

  *  ring-type: cobwebby=c,evanescent=e,flaring=f,large=l,none=n,pendant=p,sheathing=s,zone=z

  *  spore-print-color: black=k,brown=n,buff=b,chocolate=h,green=r,orange=o,purple=u,white=w,yellow=y

  *  population: abundant=a,clustered=c,numerous=n,scattered=s,several=v,solitary=y

  *  habitat: grasses=g,leaves=l,meadows=m,paths=p,urban=u,waste=w,woods=d


In [2]:
mushroom.shape

(8124, 23)

In [3]:
mushroom['class'].value_counts()

e    4208
p    3916
Name: class, dtype: int64

Pretty even!!

In [17]:
mushroom.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

### Data preprocessing

In [4]:
from sklearn import preprocessing as pp

mushroom_values = mushroom.values
le = pp.LabelEncoder()

le.fit(mushroom_values[:,0])
mushroom_encoded = le.transform(mushroom_values[:,0])

for i in range(1, mushroom.shape[1]):
    le.fit(mushroom_values[:,i])
    mushroom_encoded = np.vstack((mushroom_encoded,le.transform(mushroom_values[:,i])))
    

mushroom_encoded = mushroom_encoded.T
mushroom_encoded.shape

(8124, 23)

In [5]:
list(mushroom.columns.values)

['class',
 'cap-shape',
 'cap-surface',
 'cap-color',
 'bruises',
 'odor',
 'gill-attachment',
 'gill-spacing',
 'gill-size',
 'gill-color',
 'stalk-shape',
 'stalk-root',
 'stalk-surface-above-ring',
 'stalk-surface-below-ring',
 'stalk-color-above-ring',
 'stalk-color-below-ring',
 'veil-type',
 'veil-color',
 'ring-number',
 'ring-type',
 'spore-print-color',
 'population',
 'habitat']

#### En easier way

In [19]:
for col in mushroom.columns:
    mushroom[col] = le.fit_transform(mushroom[col])

In [20]:
mushroom.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color   ...     stalk-surface-below-ring  \
0             0          1           4   ...                            2   
1             0          0           4   ...                            2   
2             0          0           5   ...                            2   
3             0          1           5   ...                            2   
4             1          0           4   ...                            2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

### Train test split

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(mushroom_encoded[:,1:], mushroom_encoded[:,0], test_size=0.2, random_state=42)

### Decision tree classifier implementation

In [7]:
from sklearn.tree import DecisionTreeClassifier


dtc = DecisionTreeClassifier(random_state = 42)

start_dtc = time.time()
dtc.fit(X_train, y_train)
end_dtc = time.time()

print('Time to train decision tree classifier: %0.4fs' % (end_dtc - start_dtc))

Time to train decision tree classifier: 0.0196s


In [8]:
dtc.feature_importances_

array([ 0.        ,  0.        ,  0.        ,  0.02777269,  0.03746317,
        0.        ,  0.        ,  0.11671717,  0.33692629,  0.02322861,
        0.00970566,  0.        ,  0.00189668,  0.        ,  0.01835419,
        0.        ,  0.00400568,  0.00265157,  0.        ,  0.21302621,
        0.18064443,  0.02760765])

In [9]:
from sklearn.model_selection import cross_val_score

clf = DecisionTreeClassifier(random_state=0)
cross_val_score(clf, mushroom_encoded[:,1:], mushroom_encoded[:,0], cv=10)

array([ 0.68511685,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  0.98520345,  1.        ])

In [10]:
dtc.score(X_test, y_test)

1.0

In [11]:
y_prob = dtc.predict_proba(X_test)[:,1]
y_pred = np.where(y_prob > 0.5, 1, 0)

In [12]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))

[[843   0]
 [  0 782]]


### Random forest classifier implementation

In [13]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators = 100, n_jobs = -1, random_state = 42)

start_rfc = time.time()
rfc.fit(X_train, y_train)
end_rfc = time.time()

print('Time to train random forest classifier: %0.4fs' % (end_rfc - start_rfc))

Time to train random forest classifier: 0.2917s


In [14]:
cross_val_score(rfc, mushroom_encoded[:, 1:], mushroom_encoded[:,0], cv=10)

array([ 0.68511685,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  0.98890259,  1.        ])

In [15]:
rfc.score(X_test, y_test)

1.0

In [16]:
y_prob = rfc.predict_proba(X_test)[:,1]
y_pred = np.where(y_prob > 0.5, 1, 0)
print(confusion_matrix(y_test, y_pred))

[[843   0]
 [  0 782]]


### Logistic regression implementation

In [21]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
start_lr = time.time()
lr.fit(X_train, y_train)
end_lr = time.time()

print('Time to train logistic regression classifier: %0.4fs' % (end_lr - start_lr))

Time to train logistic regression classifier: 0.4555s


In [22]:
cross_val_score(lr, mushroom_encoded[:, 1:], mushroom_encoded[:,0], cv=10)

array([ 0.6703567 ,  0.85854859,  0.98154982,  0.98523985,  0.89544895,
        0.86100861,  0.99876847,  0.99630542,  0.62762022,  0.93958076])

In [23]:
lr.score(X_test, y_test)

0.94646153846153847

In [24]:
y_prob = lr.predict_proba(X_test)[:, 1]
y_pred = np.where(y_prob > 0.5, 1, 0)
print(confusion_matrix(y_test, y_pred))

[[798  45]
 [ 42 740]]
